name: CI

on:
  push:
    branches: ['dev']

jobs:
  build:
    name: update version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7.12.2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: pnpm install

      - name: Update Version
        run: pnpm run v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
