name: CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Please select the type to publish
        required: true
        type: choice
        options:
          - alpha
          - beta
          - latest
        default: 'latest'

jobs:
  build:
    name: update version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7.12.2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: pnpm install

      - name: Update Version
        run: pnpm run v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Packages
        run: pnpm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update changelog message
          title: Update Changelog title
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: main
