name: Release

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ github.ref }} ${{ github.head_ref }}
