name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: startsWith(github.head_ref, 'releases/') && github.event.pull_request.merged == true
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ github.ref }} ${{ github.head_ref }} ${{ github.event.pull_request.merged }}

      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7.12.2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: pnpm install

      - name: Publish Packages
        run: pnpm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Tags
        run: |
          git push --follow-tags
