name: Release

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Publish Packages
        run: pnpm run publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Push Tag
        run: git push --flows-tags

