name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ github.ref }} ${{ github.head_ref }} ${{ github.event.pull_request.merged }}
